### ISSUE TITLE
Support firefox desktop benchmark test needn't via installer

### ISSUE THREAD

**Issue by daoshengmu** [mozilla-b2g/mozbench#19]
Currently, Firefox benchmark test has to be through installer but Chrome needn't. We should figure out the reason. Moreover, MacOS seems to not support this methodology. If we could run Firefox benchmark test through application directly. That probably would solve some relative problems.

**Comment by TheKK** [comment]
One possible reason for installing firefox every time could be that we have to
make sure our testing target is pure. It's possible (and easy) to make mozbench
run pre-installed firefox, but we can not guarantee that there's no other
factors, like heavy add-on, would affect the result of benchmarks.

**Comment by dminor** [comment]
I'm working on fixing this soon. Mozbench will take a path to the firefox install to run and I'll use mozdownload to download a nightly through the Jenkins scripts.

**Comment by dminor** [comment]
This should be fixed by bb7491b1c536c0ca4d1a2bc78bf0b061d8b47059

**Comment by daoshengmu** [comment]
@dminor. I have tested this merge. I works well! Thanks a lot.

**Comment by TheKK** [comment]
This feature still not land on Android devices. Is this meant to be or will be solved in the future?

**Comment by dminor** [comment]
Sure, if that would be helpful to you, I can make the Android changes as well.
